### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Master05710** [st1vms/unofficial-claude2-api#11]
Python 3.9.18 (main, Aug 25 2023, 13:20:04)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from claude2_api import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/claude2_api/__init__.py", line 2, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/dist-packages/claude2_api/client.py", line 21,
in <module>
    from .session import SessionData
  File "/usr/local/lib/python3.9/dist-packages/claude2_api/session.py", line 41, in <module>
    def get_session_data(profile: str = "", quiet: bool = False) -> SessionData
| None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by st1vms** [comment]
This error comes from the fact that you are using python 3.9, and the `type | None` syntax was introduced in Python>=3.10

Anyways I should update the setup.py to reflect the correct minimum version of Python3...sorry for troubles.
